***xGBoost Practice***

In [1]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd 

In [2]:
df = pd.read_csv('../input/deep_Learning_for_time_series_forecasting_datasets/pima-indians-diabetes.csv', index_col=None, header=None)
df = df.values
X = df[:,0:8]
Y = df[:,8]
validation_set = 0.2
seed = 7
X_train, X_validation,Y_train, Y_validation = train_test_split(X,Y, 
    test_size=validation_set, random_state=seed)
model = XGBClassifier(max_depth = 3, n_estimators = 100)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
predictions
accuracy_score(Y_validation, predictions)


0.7532467532467533

In [3]:
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('../input/deep_Learning_for_time_series_forecasting_datasets/iris.csv', header=None, index_col=None)
df = df.values
X = df[:,0:4]
Y = df[:,4]

label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y = label_encoder.transform(Y)

seed = 42
validation_set = 0.2
X_train, X_validation, Y_train, Y_validation = train_test_split(X, label_encoded_y, test_size=validation_set, random_state=seed)
model = XGBClassifier()
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
predictions


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [4]:
accuracy = accuracy_score(Y_validation, predictions)
accuracy

1.0

In [5]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_validation, predictions))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [6]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('../input/kaggle/breast_cancer/breast-cancer.data', header=None, index_col=None)
df = df.values

# split dataset
X = df[:,1:]
X = X.astype(str)
Y = df[:,0]

columns = []

for i in range(0, X.shape[1]):
    label_encoder = LabelEncoder()
    feature = label_encoder.fit_transform(X[:,i])
    feature = feature.reshape(X.shape[0],1)
    onehot_encoder = OneHotEncoder(sparse_output = False)
    feature = onehot_encoder.fit_transform(feature)
    columns.append(feature)

encoded_X = np.column_stack(columns)
print(f'X Shape:{encoded_X.shape}')

label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoder_y = label_encoder.transform(Y)

seed = 7
validation_set = 0.2

X_train, X_validation, Y_train, Y_validation = train_test_split(encoded_X, 
                                                                label_encoder_y, 
                                                                random_state=seed, 
                                                                test_size=validation_set)
model = XGBClassifier(max_depth=3, n_estimators = 100)
model.fit(X_train, Y_train,)
predictions = model.predict(X_validation)
accuracy = accuracy_score(Y_validation, predictions)
accuracy


X Shape:(286, 43)


0.7241379310344828

In [7]:
# binary classification, missing data
from pandas import read_csv
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
# load data
dataframe = pd.read_csv('../input/deep_Learning_for_time_series_forecasting_datasets/horse-colic.csv', header=None)
dataset = dataframe.values
# split data into X and y
X = dataset[:,0:27]
Y = dataset[:,27]
# set missing values to 0
X[X == '?'] = np.nan
# convert to numeric
X = X.astype('float32')
# encode Y class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y = label_encoder.transform(Y)
# split data into train and test sets
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, label_encoded_y,
test_size=test_size, random_state=seed)
# fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)
print(model)
# make predictions for test data
predictions = model.predict(X_test)
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)
Accuracy: 84.85%


In [8]:
# binary classification, missing data
from pandas import read_csv
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import numpy as np

# load data
dataframe = pd.read_csv('../input/deep_Learning_for_time_series_forecasting_datasets/horse-colic.csv', header=None)
dataset = dataframe.values
# split data into X and y
X = dataset[:,0:27]
Y = dataset[:,27]
# set missing values to NaN
X[X == '?'] = np.nan
# convert to numeric
X = X.astype('float32')
# impute missing values as the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputed_x = imputer.fit_transform(X)
# encode Y class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y = label_encoder.transform(Y)
# split data into train and test sets
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(imputed_x, label_encoded_y,
test_size=test_size, random_state=seed)
# fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)
# make predictions for test data
predictions = model.predict(X_test)
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 81.82%


In [9]:
# k-fold cross validation evaluation of xgboost model
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

df = pd.read_csv('../input/deep_Learning_for_time_series_forecasting_datasets/pima-indians-diabetes.csv', index_col=None, header=None)
df = df.values
X = df[:,0:8]
Y = df[:,8]

model = XGBClassifier()
kfold = KFold(n_splits=10)
results = cross_val_score(model, X, Y, cv=kfold)
print(f'Accuracy: {results.mean()*100}% ({results.std()*100}%)')

Accuracy: 74.21736158578265% (5.751549704228197%)


In [10]:
# k-fold cross validation evaluation of xgboost model
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

df = pd.read_csv('../input/deep_Learning_for_time_series_forecasting_datasets/pima-indians-diabetes.csv', index_col=None, header=None)
df = df.values
X = df[:,0:8]
Y = df[:,8]

model = XGBClassifier()
kfold = StratifiedKFold(n_splits=10)
results = cross_val_score(model, X, Y, cv=kfold)
print(f'Accuracy: {results.mean()*100}% ({results.std()*100}%)')

Accuracy: 74.34723171565277% (4.208341180955764%)


In [12]:
df = pd.read_csv(f'D:/Grenoble INP-SIE/Semester 3/Data Analytics/Mobility Project/allgre.PB_V2.RData')
df

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte